name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ['1.23', '1.24']
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
  
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.goVer }}
       
    - name: Test
      run: go test  -coverprofile=coverage1.txt ./...

    - name: Test Generic
      run: go test -tags purego -coverprofile=coverage2.txt ./...      

    - name: Upload results to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage1.txt,./coverage2.txt
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
